### ISSUE TITLE
Inserted / pushed ArrayField is not pristine

### ISSUE THREAD

**Issue by maciejmyslinski** [final-form/final-form-arrays#23]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

We have an array of fruits.
Initial values are: `[]`

##### Steps to reproduce:

1. click insert(0, '') or push('') button.

When an Array Field mounts for the first time with insert or push, it's NOT pristine.

### What is the expected behavior?

When a normal Field mounts for the first time, it's pristine. I would expect every inserted or pushed input to be pristine as well.

### Sandbox Link

[![Edit 🐛 Inserted/pushed ArrayField is not pristine](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54kx353814)

### What's your environment?

| package | version |
| --- | --- |
| final-form | 4.11 |
| react-final-form | 4.0.2 |
| final-form-arrays | 1.1.1 |
| react-final-form-arrays | 2.0.1 |

**Comment by erikras** [comment]
This is not really a bug. If you `insert(0, undefined)` or `push(undefined)`, they are pristine. That's how non-array fields appear `pristine` on first render. The way `final-form` handles `''` and `undefined` is [complex and intentional](https://github.com/final-form/final-form/blob/master/docs/faq.md#why-does--final-form-set-my--field-value-to-undefined).
